packages:
  - .

overrides:
  '@isaacs/brace-expansion': 5.0.7
  'ajv@^6.0.0': 6.14.0
  'ajv@^8.0.0': 8.18.0
  'axios@<1.0.0': 0.32.0
  body-parser: 2.2.1
  'brace-expansion@^1.0.0': 1.1.13
  'brace-expansion@^2.0.0': 2.0.3
  'fast-uri@^3.0.0': 3.1.2
  'file-type@^21.0.0': 21.3.2
  follow-redirects: 1.16.0
  form-data: 4.0.6
  'js-yaml@^4.0.0': 4.2.0
  lodash: 4.18.1
  'minimatch@^3.0.0': 3.1.4
  'minimatch@^9.0.0': 9.0.7
  'minimatch@^10.0.0': 10.2.5
  multer: 2.2.0
  path-to-regexp: 8.4.2
  'picomatch@^2.0.0': 2.3.2
  'picomatch@^4.0.0': 4.0.5
  'piscina@^4.0.0': 4.9.3
  qs: 6.15.3
  validator: 13.15.22

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  dtrace-provider: true
  prisma: true
